#ifndef _LEXEME_ID
#define _LEXEME_ID



#define LEXEME_ID_CLASS 275
#define LEXEME_ID_END 298

#define LEXEME_ID_PRE 369
#define LEXEME_ID_POST 0
#define LEXEME_ID_LET 339
#define LEXEME_ID_IF 317
#define LEXEME_ID_THEN 410
#define LEXEME_ID_IN 319
#define LEXEME_ID_ELSEIF 297
#define LEXEME_ID_ELSE 296
#define LEXEME_ID_AND 262
#define LEXEME_ID_OR 363

#define LEXEME_ID_TRUE 430
#define LEXEME_ID_FALSE 429

//記号
#define LEXEME_ID_LANGLE 40
#define LEXEME_ID_RANGLE 41
#define LEXEME_ID_COMMA 44
#define LEXEME_ID_SEMICOLON 59
#define LEXEME_ID_TWO_EQUAL 333
#define LEXEME_ID_EQUAL 299
#define LEXEME_ID_RIGHT_ARRAY 264


//変数型
#define LEXEME_ID_BOOL 270


//修飾子
#define LEXEME_ID_PUBLIC 375
#define LEXEME_ID_PRIVATE 0
#define LEXEME_ID_PROTECTED -1
#define LEXEME_ID_STATIC 403

//定義
#define LEXEME_ID_TYPES 420
#define LEXEME_ID_VALUES -2
#define LEXEME_ID_INSTANCE_VARIABLES -3
#define LEXEME_ID_FUNCTIONS 312
#define LEXEME_ID_OPERATIONS 361
#define LEXEME_ID_SYNC -5
#define LEXEME_ID_THREAD -6


#endif